version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=senhaRoot
      - MYSQL_DATABASE=planilha_sptech
      - MYSQL_USER=ze
      - MYSQL_PASSWORD=senhaDoZe
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: